# Generated by Django 4.2.7 on 2023-11-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceTracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
