# Generated by Django 4.2.5 on 2023-12-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AttendanceTracker', '0002_delete_course_delete_student_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=32)),
            ],
        ),
    ]
