# Generated by Django 4.2.6 on 2023-11-04 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_role_user_roleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sectionID',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseID',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='sectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassSectionID', to='accounts.section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='sectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnrollSectionID', to='accounts.section'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='sectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TAsectionID', to='accounts.section'),
        ),
    ]
