# Generated by Django 4.2.6 on 2023-11-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_section_remove_course_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='checkincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
