# Generated by Django 4.2.6 on 2023-11-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_classes_checkincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='checkincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
